---
# https://megalinter.io/latest/configuration/
DISABLE_ERRORS_LINTERS:
  - SPELL_CSPELL
  - REPOSITORY_TRIVY
  - REPOSITORY_CHECKOV
  - TERRAFORM_CHECKOV
  - TERRAFORM_TERRASCAN
  - TERRAFORM_KICS
